version: '3'
volumes:
  dados:
networks:
  banco:
  web:  
services:
  db: 
    image: postgres:12.3
    volumes:
      # Volume dos dados
      - dados:/var/lib/postgresql/data
      # Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - banco
    environment:     
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD="postgres"         
  frontend:
    image: nginx:1.13
    volumes:
      # Site
      - ./web:/usr/share/nginx/html/
      # Configuração do proxy reverso
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf     
    ports:
      - 8080:80
    networks:
      - web
    depends_on:
      - app
  app:
    image: python:3.6
    volumes:
      # Site
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    networks:
      - banco
      - web     
    depends_on:
      - db



    

